services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file:
      - .env
  users-service:
    build:
      context: .
      dockerfile: users-service/Dockerfile
    env_file:
      - .env
