CREATE TABLE IF NOT EXISTS users (
	uuid TEXT PRIMARY KEY,
	best_task INT NOT NULL DEFAULT 0,
	worst_task INT NOT NULL DEFAULT 0,
	streak BIGINT NOT NULL DEFAULT 0,
	level TEXT NOT NULL DEFAULT 'A1',
	task_id INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_id ON users(uuid);
