syntax = "proto3";

package ai;
option go_package = "generated-ai/;aiservice";

message GenerateTextReq {
  int64 uuid = 1;
  string prompt = 2;
  string system_prompt = 3;
  string request_trace = 4;
}
message GenerateTextRes {
  string text = 1;
}

message GenerateAudioReq {
  string text = 1;
  string request_trace = 2;
}
message GenerateAudioRes {
  bytes audio_data = 1;
}

message RecognizeAudioReq {
  bytes audio_data = 1;
  string request_trace = 2;
}
message RecognizeAudioRes {
  string text = 1;
}

service AIService {
  rpc GenerateText (GenerateTextReq) returns (stream GenerateTextRes);
  rpc GenerateAudio (GenerateAudioReq) returns (GenerateAudioRes);
  rpc RecognizeAudio (RecognizeAudioReq) returns (stream RecognizeAudioRes);
}
