syntax = "proto3";

package learn;
option go_package = "generated-learn/;learnservice";

// TASKS MESSAGES

message NewTaskReq {
  string json_data = 1; // full page
}
message NewTaskRes {
  string level = 1; // task level
  string task_uuid = 2; // created uuid
}

message GetTaskReq {
  string task_uuid = 1;
}
message GetTaskRes {
  string task = 1;
  string level = 2;
  string answer = 3;
}

message DelTaskReq {
  string task_uuid = 1;
}
message DelTaskRes {}

// WORDS MESSAGES

message NewWordsReq {
  string json_words = 1; // many words in json format
}
message NewWordsRes {}

message GetWordReq {
  string word = 1;
}
message GetWordRes {
  string word = 1;
  string level = 2;
  string first_letter = 3;
}

message DelWordReq {
  string word = 1;
}
message DelWordRes {}

service LearnService {
  rpc NewTask (NewTaskReq) returns (NewTaskRes);
  rpc GetTask (GetTaskReq) returns (GetTaskRes);
  rpc DelTask (DelTaskReq) returns (DelTaskRes);

  rpc NewWords (NewWordsReq) returns (NewWordsRes);
  rpc GetWord (GetWordReq) returns (GetWordRes);
  rpc DelWord (DelWordReq) returns (DelWordRes);
}
