syntax = "proto3";

package users;
option go_package="generated-users/;usersservice";

message RegReq {
  int64 uuid = 1;
  string request_trace = 2;
}
message RegRes {}

message GetReq {
  int64 uuid = 1;
  string request_trace = 2;
}
message GetRes {
  string data = 1; // json
}

message UpdReq {
  string data = 1; // json
  string request_trace = 2;
}
message UpdRes {}

message DelReq {
  int64 uuid = 1;
  string request_trace = 2;
}
message DelRes {}

service UsersService {
  rpc RegUser (RegReq) returns (RegRes);
  rpc GetUser (GetReq) returns (GetRes);
  rpc UpdUser (UpdReq) returns (UpdRes);
  rpc DelUser (DelReq) returns (DelRes);
}
