syntax = "proto3";

package users;
option go_package="generated-users/;usersservice";

message RegReq {
  int64 uuid = 1;
  string request_trace = 2;
}
message RegRes {}

message GetReq {
  int64 uuid = 1;
  string request_trace = 2;
}
message GetRes {
  string data = 1; // json
}

message UpdSystemPromptReq {
  string system_prompt = 1;
  string request_trace = 2;
}
message UpdSystemPromptRes {}

message DelReq {
  int64 uuid = 1;
  string request_trace = 2;
}
message DelRes {}

service UsersService {
  rpc RegUser (RegReq) returns (RegRes);
  rpc GetUser (GetReq) returns (GetRes);
  rpc UpdSystemPrompt (UpdSystemPromptReq) returns (UpdSystemPromptRes);
  rpc DelUser (DelReq) returns (DelRes);
}
