syntax = "proto3";

package users;
option go_package="generated-users/;usersservice";

message RegReq {
  int64 uuid = 1;
  string request_trace = 2;
}
message RegRes {}

message GetReq {
  int64 uuid = 1;
  string request_trace = 2;
}
message GetRes {
  int32 best_task = 1;
  int32 worst_task = 2;
  int64 streak = 3;
  string level = 4;
  int32 task_id = 5;
}

message DelReq {
  string uuid = 1;
  string request_trace = 2;
}
message DelRes {}

service UsersService {
  rpc RegUser (RegReq) returns (RegRes);
  rpc GetUser (GetReq) returns (GetRes);
  rpc DelUser (DelReq) returns (DelRes);
}
