// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ai.proto

package aiservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,3,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReq) Reset() {
	*x = GenerateReq{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReq) ProtoMessage() {}

func (x *GenerateReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReq.ProtoReflect.Descriptor instead.
func (*GenerateReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GenerateReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type GenerateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRes) Reset() {
	*x = GenerateRes{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRes) ProtoMessage() {}

func (x *GenerateRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRes.ProtoReflect.Descriptor instead.
func (*GenerateRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRes) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"Z\n" +
	"\vGenerateReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\rrequest_trace\x18\x03 \x01(\tR\frequestTrace\"!\n" +
	"\vGenerateRes\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text29\n" +
	"\tAIService\x12,\n" +
	"\bGenerate\x12\x0f.ai.GenerateReq\x1a\x0f.ai.GenerateResB\x19Z\x17generated-ai/;aiserviceb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_proto_goTypes = []any{
	(*GenerateReq)(nil), // 0: ai.GenerateReq
	(*GenerateRes)(nil), // 1: ai.GenerateRes
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: ai.AIService.Generate:input_type -> ai.GenerateReq
	1, // 1: ai.AIService.Generate:output_type -> ai.GenerateRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
