// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: users.proto

package usersservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          int64                  `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,2,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegReq) Reset() {
	*x = RegReq{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegReq) ProtoMessage() {}

func (x *RegReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegReq.ProtoReflect.Descriptor instead.
func (*RegReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *RegReq) GetUuid() int64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *RegReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type RegRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegRes) Reset() {
	*x = RegRes{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegRes) ProtoMessage() {}

func (x *RegRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegRes.ProtoReflect.Descriptor instead.
func (*RegRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          int64                  `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,2,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetReq) GetUuid() int64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *GetReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type GetRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BestTask      int32                  `protobuf:"varint,1,opt,name=best_task,json=bestTask,proto3" json:"best_task,omitempty"`
	WorstTask     int32                  `protobuf:"varint,2,opt,name=worst_task,json=worstTask,proto3" json:"worst_task,omitempty"`
	Streak        int64                  `protobuf:"varint,3,opt,name=streak,proto3" json:"streak,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	TaskId        int32                  `protobuf:"varint,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRes) Reset() {
	*x = GetRes{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRes) ProtoMessage() {}

func (x *GetRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRes.ProtoReflect.Descriptor instead.
func (*GetRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *GetRes) GetBestTask() int32 {
	if x != nil {
		return x.BestTask
	}
	return 0
}

func (x *GetRes) GetWorstTask() int32 {
	if x != nil {
		return x.WorstTask
	}
	return 0
}

func (x *GetRes) GetStreak() int64 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *GetRes) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *GetRes) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type DelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          int64                  `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RequestTrace  string                 `protobuf:"bytes,2,opt,name=request_trace,json=requestTrace,proto3" json:"request_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelReq) Reset() {
	*x = DelReq{}
	mi := &file_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelReq) ProtoMessage() {}

func (x *DelReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelReq.ProtoReflect.Descriptor instead.
func (*DelReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{4}
}

func (x *DelReq) GetUuid() int64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *DelReq) GetRequestTrace() string {
	if x != nil {
		return x.RequestTrace
	}
	return ""
}

type DelRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRes) Reset() {
	*x = DelRes{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRes) ProtoMessage() {}

func (x *DelRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRes.ProtoReflect.Descriptor instead.
func (*DelRes) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{5}
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x05users\"A\n" +
	"\x06RegReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\x03R\x04uuid\x12#\n" +
	"\rrequest_trace\x18\x02 \x01(\tR\frequestTrace\"\b\n" +
	"\x06RegRes\"A\n" +
	"\x06GetReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\x03R\x04uuid\x12#\n" +
	"\rrequest_trace\x18\x02 \x01(\tR\frequestTrace\"\x8b\x01\n" +
	"\x06GetRes\x12\x1b\n" +
	"\tbest_task\x18\x01 \x01(\x05R\bbestTask\x12\x1d\n" +
	"\n" +
	"worst_task\x18\x02 \x01(\x05R\tworstTask\x12\x16\n" +
	"\x06streak\x18\x03 \x01(\x03R\x06streak\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\x05R\x06taskId\"A\n" +
	"\x06DelReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\x03R\x04uuid\x12#\n" +
	"\rrequest_trace\x18\x02 \x01(\tR\frequestTrace\"\b\n" +
	"\x06DelRes2\x89\x01\n" +
	"\fUsersService\x12'\n" +
	"\aRegUser\x12\r.users.RegReq\x1a\r.users.RegRes\x12'\n" +
	"\aGetUser\x12\r.users.GetReq\x1a\r.users.GetRes\x12'\n" +
	"\aDelUser\x12\r.users.DelReq\x1a\r.users.DelResB\x1fZ\x1dgenerated-users/;usersserviceb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_users_proto_goTypes = []any{
	(*RegReq)(nil), // 0: users.RegReq
	(*RegRes)(nil), // 1: users.RegRes
	(*GetReq)(nil), // 2: users.GetReq
	(*GetRes)(nil), // 3: users.GetRes
	(*DelReq)(nil), // 4: users.DelReq
	(*DelRes)(nil), // 5: users.DelRes
}
var file_users_proto_depIdxs = []int32{
	0, // 0: users.UsersService.RegUser:input_type -> users.RegReq
	2, // 1: users.UsersService.GetUser:input_type -> users.GetReq
	4, // 2: users.UsersService.DelUser:input_type -> users.DelReq
	1, // 3: users.UsersService.RegUser:output_type -> users.RegRes
	3, // 4: users.UsersService.GetUser:output_type -> users.GetRes
	5, // 5: users.UsersService.DelUser:output_type -> users.DelRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
