// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: learn.proto

package learnservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskData      string                 `protobuf:"bytes,1,opt,name=task_data,json=taskData,proto3" json:"task_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTaskReq) Reset() {
	*x = NewTaskReq{}
	mi := &file_learn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTaskReq) ProtoMessage() {}

func (x *NewTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTaskReq.ProtoReflect.Descriptor instead.
func (*NewTaskReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{0}
}

func (x *NewTaskReq) GetTaskData() string {
	if x != nil {
		return x.TaskData
	}
	return ""
}

type NewTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	TaskId        int32                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskUuid      string                 `protobuf:"bytes,4,opt,name=task_uuid,json=taskUuid,proto3" json:"task_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTaskRes) Reset() {
	*x = NewTaskRes{}
	mi := &file_learn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTaskRes) ProtoMessage() {}

func (x *NewTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTaskRes.ProtoReflect.Descriptor instead.
func (*NewTaskRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{1}
}

func (x *NewTaskRes) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *NewTaskRes) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *NewTaskRes) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *NewTaskRes) GetTaskUuid() string {
	if x != nil {
		return x.TaskUuid
	}
	return ""
}

type GetTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUuid      string                 `protobuf:"bytes,1,opt,name=task_uuid,json=taskUuid,proto3" json:"task_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReq) Reset() {
	*x = GetTaskReq{}
	mi := &file_learn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReq) ProtoMessage() {}

func (x *GetTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReq.ProtoReflect.Descriptor instead.
func (*GetTaskReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskReq) GetTaskUuid() string {
	if x != nil {
		return x.TaskUuid
	}
	return ""
}

type GetTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	TaskId        int32                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRes) Reset() {
	*x = GetTaskRes{}
	mi := &file_learn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRes) ProtoMessage() {}

func (x *GetTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRes.ProtoReflect.Descriptor instead.
func (*GetTaskRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRes) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *GetTaskRes) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *GetTaskRes) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type DelTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUuid      string                 `protobuf:"bytes,1,opt,name=task_uuid,json=taskUuid,proto3" json:"task_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelTaskReq) Reset() {
	*x = DelTaskReq{}
	mi := &file_learn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTaskReq) ProtoMessage() {}

func (x *DelTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTaskReq.ProtoReflect.Descriptor instead.
func (*DelTaskReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{4}
}

func (x *DelTaskReq) GetTaskUuid() string {
	if x != nil {
		return x.TaskUuid
	}
	return ""
}

type DelTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelTaskRes) Reset() {
	*x = DelTaskRes{}
	mi := &file_learn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTaskRes) ProtoMessage() {}

func (x *DelTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTaskRes.ProtoReflect.Descriptor instead.
func (*DelTaskRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{5}
}

type NewWordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewWordReq) Reset() {
	*x = NewWordReq{}
	mi := &file_learn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewWordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWordReq) ProtoMessage() {}

func (x *NewWordReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWordReq.ProtoReflect.Descriptor instead.
func (*NewWordReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{6}
}

func (x *NewWordReq) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type NewWordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	FirstLetter   string                 `protobuf:"bytes,3,opt,name=first_letter,json=firstLetter,proto3" json:"first_letter,omitempty"`
	WordUuid      string                 `protobuf:"bytes,4,opt,name=word_uuid,json=wordUuid,proto3" json:"word_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewWordRes) Reset() {
	*x = NewWordRes{}
	mi := &file_learn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewWordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWordRes) ProtoMessage() {}

func (x *NewWordRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWordRes.ProtoReflect.Descriptor instead.
func (*NewWordRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{7}
}

func (x *NewWordRes) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *NewWordRes) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *NewWordRes) GetFirstLetter() string {
	if x != nil {
		return x.FirstLetter
	}
	return ""
}

func (x *NewWordRes) GetWordUuid() string {
	if x != nil {
		return x.WordUuid
	}
	return ""
}

type GetWordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordUuid      string                 `protobuf:"bytes,1,opt,name=word_uuid,json=wordUuid,proto3" json:"word_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordReq) Reset() {
	*x = GetWordReq{}
	mi := &file_learn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordReq) ProtoMessage() {}

func (x *GetWordReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordReq.ProtoReflect.Descriptor instead.
func (*GetWordReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{8}
}

func (x *GetWordReq) GetWordUuid() string {
	if x != nil {
		return x.WordUuid
	}
	return ""
}

type GetWordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	FirstLetter   string                 `protobuf:"bytes,3,opt,name=first_letter,json=firstLetter,proto3" json:"first_letter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordRes) Reset() {
	*x = GetWordRes{}
	mi := &file_learn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordRes) ProtoMessage() {}

func (x *GetWordRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordRes.ProtoReflect.Descriptor instead.
func (*GetWordRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{9}
}

func (x *GetWordRes) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *GetWordRes) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *GetWordRes) GetFirstLetter() string {
	if x != nil {
		return x.FirstLetter
	}
	return ""
}

type DelWordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordUuid      string                 `protobuf:"bytes,1,opt,name=word_uuid,json=wordUuid,proto3" json:"word_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelWordReq) Reset() {
	*x = DelWordReq{}
	mi := &file_learn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelWordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelWordReq) ProtoMessage() {}

func (x *DelWordReq) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelWordReq.ProtoReflect.Descriptor instead.
func (*DelWordReq) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{10}
}

func (x *DelWordReq) GetWordUuid() string {
	if x != nil {
		return x.WordUuid
	}
	return ""
}

type DelWordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelWordRes) Reset() {
	*x = DelWordRes{}
	mi := &file_learn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelWordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelWordRes) ProtoMessage() {}

func (x *DelWordRes) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelWordRes.ProtoReflect.Descriptor instead.
func (*DelWordRes) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{11}
}

var File_learn_proto protoreflect.FileDescriptor

const file_learn_proto_rawDesc = "" +
	"\n" +
	"\vlearn.proto\x12\x05learn\")\n" +
	"\n" +
	"NewTaskReq\x12\x1b\n" +
	"\ttask_data\x18\x01 \x01(\tR\btaskData\"l\n" +
	"\n" +
	"NewTaskRes\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x05R\x06taskId\x12\x1b\n" +
	"\ttask_uuid\x18\x04 \x01(\tR\btaskUuid\")\n" +
	"\n" +
	"GetTaskReq\x12\x1b\n" +
	"\ttask_uuid\x18\x01 \x01(\tR\btaskUuid\"O\n" +
	"\n" +
	"GetTaskRes\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x05R\x06taskId\")\n" +
	"\n" +
	"DelTaskReq\x12\x1b\n" +
	"\ttask_uuid\x18\x01 \x01(\tR\btaskUuid\"\f\n" +
	"\n" +
	"DelTaskRes\" \n" +
	"\n" +
	"NewWordReq\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"v\n" +
	"\n" +
	"NewWordRes\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12!\n" +
	"\ffirst_letter\x18\x03 \x01(\tR\vfirstLetter\x12\x1b\n" +
	"\tword_uuid\x18\x04 \x01(\tR\bwordUuid\")\n" +
	"\n" +
	"GetWordReq\x12\x1b\n" +
	"\tword_uuid\x18\x01 \x01(\tR\bwordUuid\"Y\n" +
	"\n" +
	"GetWordRes\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12!\n" +
	"\ffirst_letter\x18\x03 \x01(\tR\vfirstLetter\")\n" +
	"\n" +
	"DelWordReq\x12\x1b\n" +
	"\tword_uuid\x18\x01 \x01(\tR\bwordUuid\"\f\n" +
	"\n" +
	"DelWordRes2\xb4\x02\n" +
	"\fLearnService\x12/\n" +
	"\aNewTask\x12\x11.learn.NewTaskReq\x1a\x11.learn.NewTaskRes\x12/\n" +
	"\aGetTask\x12\x11.learn.GetTaskReq\x1a\x11.learn.GetTaskRes\x12/\n" +
	"\aDelTask\x12\x11.learn.DelTaskReq\x1a\x11.learn.DelTaskRes\x12/\n" +
	"\aNewWord\x12\x11.learn.NewWordReq\x1a\x11.learn.NewWordRes\x12/\n" +
	"\aGetWord\x12\x11.learn.GetWordReq\x1a\x11.learn.GetWordRes\x12/\n" +
	"\aDelWord\x12\x11.learn.DelWordReq\x1a\x11.learn.DelWordResB\x1fZ\x1dgenerated-learn/;learnserviceb\x06proto3"

var (
	file_learn_proto_rawDescOnce sync.Once
	file_learn_proto_rawDescData []byte
)

func file_learn_proto_rawDescGZIP() []byte {
	file_learn_proto_rawDescOnce.Do(func() {
		file_learn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learn_proto_rawDesc), len(file_learn_proto_rawDesc)))
	})
	return file_learn_proto_rawDescData
}

var file_learn_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_learn_proto_goTypes = []any{
	(*NewTaskReq)(nil), // 0: learn.NewTaskReq
	(*NewTaskRes)(nil), // 1: learn.NewTaskRes
	(*GetTaskReq)(nil), // 2: learn.GetTaskReq
	(*GetTaskRes)(nil), // 3: learn.GetTaskRes
	(*DelTaskReq)(nil), // 4: learn.DelTaskReq
	(*DelTaskRes)(nil), // 5: learn.DelTaskRes
	(*NewWordReq)(nil), // 6: learn.NewWordReq
	(*NewWordRes)(nil), // 7: learn.NewWordRes
	(*GetWordReq)(nil), // 8: learn.GetWordReq
	(*GetWordRes)(nil), // 9: learn.GetWordRes
	(*DelWordReq)(nil), // 10: learn.DelWordReq
	(*DelWordRes)(nil), // 11: learn.DelWordRes
}
var file_learn_proto_depIdxs = []int32{
	0,  // 0: learn.LearnService.NewTask:input_type -> learn.NewTaskReq
	2,  // 1: learn.LearnService.GetTask:input_type -> learn.GetTaskReq
	4,  // 2: learn.LearnService.DelTask:input_type -> learn.DelTaskReq
	6,  // 3: learn.LearnService.NewWord:input_type -> learn.NewWordReq
	8,  // 4: learn.LearnService.GetWord:input_type -> learn.GetWordReq
	10, // 5: learn.LearnService.DelWord:input_type -> learn.DelWordReq
	1,  // 6: learn.LearnService.NewTask:output_type -> learn.NewTaskRes
	3,  // 7: learn.LearnService.GetTask:output_type -> learn.GetTaskRes
	5,  // 8: learn.LearnService.DelTask:output_type -> learn.DelTaskRes
	7,  // 9: learn.LearnService.NewWord:output_type -> learn.NewWordRes
	9,  // 10: learn.LearnService.GetWord:output_type -> learn.GetWordRes
	11, // 11: learn.LearnService.DelWord:output_type -> learn.DelWordRes
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_learn_proto_init() }
func file_learn_proto_init() {
	if File_learn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learn_proto_rawDesc), len(file_learn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learn_proto_goTypes,
		DependencyIndexes: file_learn_proto_depIdxs,
		MessageInfos:      file_learn_proto_msgTypes,
	}.Build()
	File_learn_proto = out.File
	file_learn_proto_goTypes = nil
	file_learn_proto_depIdxs = nil
}
